DS-17868 Add acknowledgment in README.md and update CHANGELOG.md
deep-security/chef pull request #8
Opened 2018-01-11 06:59 UTC by sudiotan

Changes:
- Add acknowledgment section in cookbook README.md.
- Regenerate CHANGELOG.md to be more readable.

2018-01-11 14:56 UTC, ChristinaSmith123 commented on deep-security-agent/README.md
> +* We thank [Blair Hamilton](https://github.com/blairham) for his contributions and put this cookbook into [Supermarket](https://supermarket.chef.io/cookbooks/deep-security-agent).
change:
'for his contributions and put this cookbook into Supermarket' -> 'for his contributions to the [Deep Security Agent cookbook] (https://supermarket.chef.io/cookbooks/deep-security-agent).'

2018-01-11 14:57 UTC, ChristinaSmith123 requested changes
Please change acknowledgment of Blair Hamilton as indicated.

2018-01-11 14:57 UTC, ChristinaSmith123 commented on deep-security-agent/README.md
> +* We thank [Blair Hamilton](https://github.com/blairham) for his contributions and put this cookbook into [Supermarket](https://supermarket.chef.io/cookbooks/deep-security-agent).
change:
'for his contributions and put this cookbook into Supermarket' -> 'for his contributions to the [Deep Security Agent cookbook] (https://supermarket.chef.io/cookbooks/deep-security-agent).'

2018-01-17 03:02 UTC, DeepSecurityOpenSourceSupport commented on deep-security-agent/CHANGELOG.md
> +## [1.1.0](https://github.com/deep-security/chef/tree/1.1.0) (2018-01-17)
As the change log will not contain the release itself, the in consist may cause confusing.
I suggest to show the release page link on github directly
https://github.com/deep-security/chef/releases

2018-01-17 03:25 UTC, merged